# Generated by Django 3.2.6 on 2022-07-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='naveLanzadera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNave', models.CharField(max_length=50)),
                ('paisNave', models.CharField(max_length=50)),
                ('pesoNave', models.CharField(max_length=50)),
                ('alturaNave', models.CharField(max_length=50)),
                ('velocidadNave', models.CharField(max_length=50)),
                ('capacidadNave', models.CharField(max_length=50)),
                ('potenciaNave', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipoNave', models.CharField(choices=[('1', 'Vehiculo Lanzadera'), ('2', 'Naves no tripuladas'), ('3', 'Naves tripuladas')], max_length=50)),
                ('tipoCarga', models.CharField(choices=[('1', 'Satelite artificial'), ('2', 'Sonda')], max_length=50)),
                ('tipoCombustible', models.CharField(choices=[('1', 'Quimico Solido'), ('2', 'Propelente Liquido')], max_length=50)),
            ],
            options={
                'verbose_name': 'Nave Lanzadera',
                'verbose_name_plural': 'Naves Lanzadera',
                'db_table': 'navesLanzadera',
            },
        ),
        migrations.CreateModel(
            name='naveNoTripulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNave', models.CharField(max_length=50)),
                ('paisNave', models.CharField(max_length=50)),
                ('pesoNave', models.CharField(max_length=50)),
                ('alturaNave', models.CharField(max_length=50)),
                ('velocidadNave', models.CharField(max_length=50)),
                ('capacidadNave', models.CharField(max_length=50)),
                ('potenciaNave', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipoNave', models.CharField(choices=[('1', 'Vehiculo Lanzadera'), ('2', 'Naves no tripuladas'), ('3', 'Naves tripuladas')], max_length=50)),
                ('cantidadMotores', models.CharField(max_length=50)),
                ('tipoPlaneta', models.CharField(choices=[('1', 'Saturno y sus lunas'), ('2', 'Jupiter'), ('3', 'Marte'), ('4', 'Mercurio'), ('5', 'pluton'), ('6', 'Urano y Neptuno'), ('7', 'Sol'), ('8', 'Venus')], max_length=50)),
            ],
            options={
                'verbose_name': 'Nave No Tripulada',
                'verbose_name_plural': 'Naves No Tripuladas',
                'db_table': 'navesNoTripulada',
            },
        ),
        migrations.CreateModel(
            name='naveTripulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNave', models.CharField(max_length=50)),
                ('paisNave', models.CharField(max_length=50)),
                ('pesoNave', models.CharField(max_length=50)),
                ('alturaNave', models.CharField(max_length=50)),
                ('velocidadNave', models.CharField(max_length=50)),
                ('capacidadNave', models.CharField(max_length=50)),
                ('potenciaNave', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipoNave', models.CharField(choices=[('1', 'Vehiculo Lanzadera'), ('2', 'Naves no tripuladas'), ('3', 'Naves tripuladas')], max_length=50)),
                ('cantidadPersonas', models.CharField(max_length=50)),
                ('tipoObjetivo', models.CharField(choices=[('1', 'Misiones Lunares'), ('2', 'Experimentación y estudio del comportamiento humano'), ('3', 'Mantenimiento de satélites')], max_length=50)),
            ],
            options={
                'verbose_name': 'Nave Tripulada',
                'verbose_name_plural': 'Naves Tripuladas',
                'db_table': 'navesTripulada',
            },
        ),
    ]
